name: release
on:
  workflow_dispatch:
  release:
    types: [published]
env:
  PACKAGE_DIR: helloworld
jobs:
  build:
    runs-on: ubuntu-latest
    name: Release package
    steps:
      - uses: actions/checkout@v2
      - name: Fetch complete history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-update-conda: true
          python-version: "3.9"
      - name: Conda stuff
        shell: bash -l {0}
        run: |
          conda info
          conda env list
          conda install conda-build anaconda-client conda-verify -y
          anaconda login --username aMahanna --password '${{ secrets.CONDA_PASSWORD }}'
          conda config --set anaconda_upload yes
          conda build .